/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Credentials, SignInResult, SignUpResult } from "../models/index";
import { CredentialsFromJSON, CredentialsToJSON, SignInResultFromJSON, SignInResultToJSON, SignUpResultFromJSON, SignUpResultToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface SignInRequest {
  credentials?: Credentials;
}

export interface SignUpRequest {
  credentials?: Credentials;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for signIn without sending the request
   */
  async signInRequestOpts(requestParameters: SignInRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/sign-in`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CredentialsToJSON(requestParameters["credentials"]),
    };
  }

  /**
   * Login with and existing account
   */
  async signInRaw(requestParameters: SignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignInResult>> {
    const requestOptions = await this.signInRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => SignInResultFromJSON(jsonValue));
  }

  /**
   * Login with and existing account
   */
  async signIn(requestParameters: SignInRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignInResult> {
    const response = await this.signInRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for signUp without sending the request
   */
  async signUpRequestOpts(requestParameters: SignUpRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/sign-up`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CredentialsToJSON(requestParameters["credentials"]),
    };
  }

  /**
   * Create new account with basic user role
   */
  async signUpRaw(requestParameters: SignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignUpResult>> {
    const requestOptions = await this.signUpRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => SignUpResultFromJSON(jsonValue));
  }

  /**
   * Create new account with basic user role
   */
  async signUp(requestParameters: SignUpRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignUpResult> {
    const response = await this.signUpRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
